version: 2
jobs:
  build:
    docker:
    - image: slacgismo/circleci_python37_base:latest
    steps:
    - checkout
    - run:
        name: Run LCM processes
        command: python rbsa.py
    - store_artifacts:
        path: /home/circleci/project/output
        destination: /rbsa
workflows:
  version: 2
  workflow:
    jobs:
    - build